---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
#download and unzip file to working directory
url <- 'https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip'
download.file(url, 'repdata_data_activity.zip')
unzip('./repdata_data_activity.zip')

#read data
data <- read.csv('activity.csv', header = TRUE)
NA_filtered <- na.omit(data)
```


## What is mean total number of steps taken per day?
```{r}
#aggregate daily data and generating histogram
steps <- aggregate(steps~date, data=data, sum, na.rm=TRUE)
hist(steps$steps, main="Total Steps per Day", xlab="steps")

#Calculating mean and median
mean_steps <- mean(steps$steps)
median_steps <- median(steps$steps)
```
```{r}
mean_steps
median_steps
```

## What is the average daily activity pattern?
```{r}
#plotting activity 
activity <- aggregate(steps ~ interval, data=data, mean, na.rm=TRUE )
plot(activity$interval, activity$steps, type='l', main = 'Activity Pattern', 
     ylab='steps', xlab='5-minute interval')
```


## Imputing missing values
```{r}
#replacing NA Values with interval mean
filled <- data
for(i in 1:nrow(data)){
  if(is.na(data$steps[i])){
    filled$steps[i] <- activity$steps[match(data$interval[i], activity$interval)]
  }
}
```

## Are there differences in activity patterns between weekdays and weekends?
```{r}
library(ggplot2)

#weekend or weekday
filled$date <- as.Date(filled$date)
filled$type <- ifelse(weekdays(filled$date) %in% c('Saturday', 'Sunday'), 
                      'weekend', 'weekday')

#plot
filled_activity_type <- aggregate(steps~interval+type, data=filled, mean)
ggplot(filled_activity_type, aes(interval, steps)) + geom_line() + facet_grid(type ~ .)
```